fixed function changed color icon heart
DidarHalla/upgrade-First pull request #3
Opened 2022-11-25 19:27 UTC by DidarHalla

2022-11-29 22:44 UTC, NovakArtsiom requested changes
в целом хоршо, чуть-чуть поправь мои комменты

2022-11-29 22:44 UTC, NovakArtsiom commented on index.css
> +.sneakersDad{
не используй `dad` или `child`. Данный способ именования не принят тк слишком абстрактный. 

.`sneakersDad`  можно заменить на `sneakersContainer`, `sneakersList`

2022-11-29 22:44 UTC, NovakArtsiom commented on index.css
> +.sneakersChild{
это может быть `sneakerItem`, `sneakerCard`, `sneakerContainer` etc
зависит от того, какую суть данный блок в себе закладывает 
он ведь не закладывает быть родителем или ребенком

2022-11-29 22:44 UTC, NovakArtsiom commented on index.js
> +    sneakersName.className = 'textAtTheBottomShoes'
сделано правильно, но проблема в именовании, я так понимаю это отвечает за описание, те может быть `cardDescription` , `itemDescription`

2022-11-29 22:44 UTC, NovakArtsiom commented on index.js
> +        if(heart == false){
сделано хорошо, как улучшение знай, что все что попадает в `if()` преобразуется в boolean, вместо `if(value===true)` можно просто `if(value)`
так же любое значение можно напрямую преобразовать в boolean, и если тебе нужно проверить, что `heart == false` можно просто написать `if(!heart)`

2022-11-29 22:44 UTC, NovakArtsiom commented on index.js
> +        if(heart == false){
https://learn.javascript.ru/logical-operators#ne

2022-11-29 22:44 UTC, NovakArtsiom commented on index.js
> +        if(heart == false){
тема как и статья эта полезная и рименяется очень часто

2022-12-01 22:37 UTC, DidarHalla commented on index.css
> +.sneakersDad{
сделано

2022-12-01 22:38 UTC, DidarHalla commented on index.css
> +.sneakersChild{
исправил на sneakerItem 👌

2022-12-01 22:39 UTC, DidarHalla commented on index.js
> +    sneakersName.className = 'textAtTheBottomShoes'
исправил на itemDescription ✌

2022-12-01 22:42 UTC, DidarHalla commented on index.js
> +        if(heart == false){
улучшил код.  За статью Благодарю ))

2022-12-06 17:46 UTC, NovakArtsiom approved these changes

2022-12-06 17:46 UTC, NovakArtsiom commented on index.js
> +        if(!heart){
 еще один момент, если у тебя есть возможность избежать логическое НЕ (!) лучше избеги, тк это увеличивает читабельность кода. 
Тут ты просто можешь поменять местами содержание блоков и убрать логическое НЕ

2022-12-07 12:19 UTC, merged