in utils.js create function getRandomDate, in cons.js add random date…
DidarHalla/upgrade-First pull request #7
Opened 2022-12-21 18:15 UTC by DidarHalla

… in arre in objekts, in index.js create sorting by date, in html add id sortByNewsItem,

2022-12-22 10:58 UTC, NovakArtsiom requested changes

2022-12-22 10:58 UTC, NovakArtsiom commented on utils.js
> +    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
что-то ты тут перемудрил, непонятно что зачем и почему. 
1. Зачем тебе параметры в функции, которые ты в итоге ни разу не используешь. Ни один вызов getRandomDate не принимает в себя аргументов. 
2. Почему тут присутвует start и end даты?
2. В чем смысл умножения и вычитания?

2022-12-22 10:58 UTC, NovakArtsiom commented on index.js
> +    }else if(target.id === 'sortByNewsItem'){
и так, вот мы и пришли когда у тебя идут if else if else и так далее
для таких случаев есть вот это https://learn.javascript.ru/switch

2022-12-22 22:44 UTC, DidarHalla commented on utils.js
> +    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
1) Это параметры по умолчанию. их в дальнейшем использую внутри самой функции. Я это сделал для читабельности. но в принципе этого же результата можно добиться такой функцией как внизу

function getResult(){
    return new Date(Math.random() * (new Date().getTime() - new Date(2018, 0, 1).getTime()) + new Date(2018, 0, 1).getTime())
}
 
2) start end определяют рамки с какого года начать и каким закончить для выбора рандом даты.
3) метод рандом выбирает между 1 и ниже т.е. на пример(0.873598734098). начну с return:
   -создаю новую дату new Date(и туда передаю результат вычитаний и умножений).
   - start.getTime(беру кол-во миллисекунд с 1970 года до 2018 г.
   - отнимаю от текущего года год с которого стартует наша дата (end.getTime() - start.getTime())
   - за тем умножаю рандомное число на остаток от нашего вычитания  Math.random() * (end.getTime() - start.getTime())
   - дальше прибавляю рандом к миллисекундам с 1970 года до 2018 г start.getTime() + Math.random()
   - в итоге получаем рандомную дату с 2018 по настоящее время

2022-12-26 07:52 UTC, NovakArtsiom commented on utils.js
> +    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
1. Читабельность этим ты не улучшил,  если я задаю вопросы по этому поводу, скорее даже больше вопросов. Если в твоей функции есть  аргументы, то они должны хотя бы где-то использоваться. В твоем случае такого нет. Это будет более читабельным, если ты сделаешь отдельные переменные с правильными названиями внутри функции. Тогда это упростит понимание кода.
2. Идею я твою понял, но в задании этого не было, поэтому стало не понятно зачем это. Тебе нужно было просто сделать случайную дату из прошлого, делается это так  `new Date(Date.now()- Math.random()*100000000000)`. Если хочешь сделать код проще, то можно разбить. `const randomDateInterval = Math.random()*100000000000; 
new Date(Date.now(randomDateInterval))
`

2022-12-26 08:00 UTC, NovakArtsiom approved these changes

2022-12-26 08:00 UTC, NovakArtsiom commented on utils.js
> +function removeThenAddContainer() {
it's not the best name, because it describes the queue of actions instead of result. Mean of the function is to reset the container / clean values of container. That'w why it can be: `cleanContainer` / `resetContainer`

2022-12-26 17:06 UTC, merged